---
name: "Building Shopping Application Image"

on:
  workflow_dispatch:

jobs:
  image-build-job:
    name: "Build AMI with Packer"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_key }}
      AWS_DEFAULT_REGION: "us-east-2"
      PACKER_VERSION: "1.14.2"

    steps:
      - name: "Repository Checkout"
        uses: actions/checkout@v5

      - name: "Installing Packer"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PACKER_VERSION }}

      - name: "Initialize Packer"
        run: packer init .
        working-directory: ./packer/

      - name: "Validate Packer Templates"
        run: packer validate .
        working-directory: ./packer/

      - name: "Build AMI Image"
        run: packer build .
        working-directory: ./packer/

